-- Database schema for ByteBuy
CREATE DATABASE IF NOT EXISTS bytebuy DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE bytebuy;

-- Users table
CREATE TABLE IF NOT EXISTS users (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL,
	full_name VARCHAR(255),
	phone VARCHAR(30),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	is_admin TINYINT(1) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Items (products)
CREATE TABLE IF NOT EXISTS items (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	sku VARCHAR(64) NOT NULL UNIQUE,
	name VARCHAR(255) NOT NULL,
	description TEXT,
	price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
	stock INT NOT NULL DEFAULT 0,
	image VARCHAR(512) DEFAULT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Orders
CREATE TABLE IF NOT EXISTS orders (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	order_code VARCHAR(32) DEFAULT NULL UNIQUE,
	user_id INT UNSIGNED NULL,
	guest_email VARCHAR(255) NULL,
	total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
	currency CHAR(3) DEFAULT 'USD',
	shipping_address TEXT,
	billing_address TEXT,
	payment_method VARCHAR(100),
	status VARCHAR(50) NOT NULL DEFAULT 'pending',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Order items / lines
CREATE TABLE IF NOT EXISTS order_items (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	order_id BIGINT UNSIGNED NOT NULL,
	item_id INT UNSIGNED NOT NULL,
	sku VARCHAR(64) NOT NULL,
	name VARCHAR(255),
	quantity INT UNSIGNED NOT NULL DEFAULT 1,
	price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_orderitems_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
	CONSTRAINT fk_orderitems_item FOREIGN KEY (item_id) REFERENCES items(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Order status changes (history)
CREATE TABLE IF NOT EXISTS order_events (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	order_id BIGINT UNSIGNED NOT NULL,
	event_type VARCHAR(100) NOT NULL,
	event_note TEXT,
	event_by INT UNSIGNED NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_ordeve_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Sessions (optional: server-side session store)
CREATE TABLE IF NOT EXISTS sessions (
	id VARCHAR(128) PRIMARY KEY,
	user_id INT UNSIGNED NULL,
	data MEDIUMTEXT,
	last_activity TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	INDEX idx_sessions_user (user_id),
	CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Helpful indexes
CREATE INDEX IF NOT EXISTS idx_items_sku_name ON items(sku, name);
CREATE INDEX IF NOT EXISTS idx_orders_user ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orderitems_order ON order_items(order_id);

-- Simple table to store platform settings if needed
CREATE TABLE IF NOT EXISTS settings (
	`key` VARCHAR(100) PRIMARY KEY,
	`value` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- End of schema

-- Carts and cart items (token-based carts, no session cookie required)
CREATE TABLE IF NOT EXISTS carts (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	token VARCHAR(128) NOT NULL UNIQUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cart_items (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	cart_id BIGINT UNSIGNED NOT NULL,
	item_id INT UNSIGNED NOT NULL,
	sku VARCHAR(64) NOT NULL,
	name VARCHAR(255) NOT NULL,
	qty INT UNSIGNED NOT NULL DEFAULT 1,
	price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
	added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_cartitems_cart FOREIGN KEY (cart_id) REFERENCES carts(id) ON DELETE CASCADE,
	CONSTRAINT fk_cartitems_item FOREIGN KEY (item_id) REFERENCES items(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
